### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by RexWzh** [RexWzh/ChatAPICall.jl#3]
- [ ] Set the time interval for each request.
- [ ] Set the response time.
- [ ] Thread pool for multi-requests.
